### ISSUE TITLE
モッタイNightページSSR使わないように変更

### ISSUE THREAD

**Issue by MK776** [KosukeSaigusa/mottai-hp-next-chakra#46]
・ホスティングサービスをcloud flareに変更
・画像の永続化(R2などのストレージに保存)
・cloud flareのSWR、ISRなど対応状況は要注意

**Comment by kosukesaigusa** [comment]
Cloudflare への GitHub Actions へのデプロイワークフローも簡単ですが、参考になれば！（Cloudflare が ISR に対応というか単に generate + deploy を任意のタイミングでトリガーできれば良さそうですね！）

https://github.com/kosukesaigusa/kosukesaigusa.com/blob/main/.github/workflows/deploy.yml
